version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - product-network

  product-service:
    build: .
    container_name: product-service
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    networks:
      - product-network

networks:
  product-network:
    driver: bridge

volumes:
  postgres-data: 